export const roadmaps = [
  // 1. QA Fundamentals
  {
    courseSlug: "qa-fundamentals",
    modules: [
      {
        id: "basics",
        title: "Основи тестування",
        order: 1,
        lessons: [
          {
            id: "1",
            slug: "intro-to-testing",
            title: "Вступ до тестування",
            courseSlug: "qa-fundamentals",
            description: "Дізнайся, що таке тестування.",
            order: 1,
            estimatedTime: 15,
            xpReward: 10,
            hasQuiz: true,
            published: true,
          },
          {
            id: "2",
            slug: "testing-types",
            title: "Типи тестування",
            courseSlug: "qa-fundamentals",
            description: "Розглянемо основні типи тестування.",
            order: 2,
            estimatedTime: 20,
            xpReward: 10,
            hasQuiz: true,
            published: true,
          },
          {
            id: "3",
            slug: "manual-testing",
            title: "Ручне тестування",
            courseSlug: "qa-fundamentals",
            description: "Навчись тестувати вручну.",
            order: 3,
            estimatedTime: 25,
            xpReward: 10,
            hasQuiz: false,
            published: true,
          },
        ],
      },
      {
        id: "automation",
        title: "Автоматизація тестів",
        order: 2,
        lessons: [
          {
            id: "4",
            slug: "automation-intro",
            title: "Вступ до автоматизації",
            courseSlug: "qa-fundamentals",
            description: "Переваги автоматизованого тестування.",
            order: 4,
            estimatedTime: 20,
            xpReward: 10,
            hasQuiz: true,
            published: true,
          },
          {
            id: "5",
            slug: "selenium-basics",
            title: "Основи Selenium",
            courseSlug: "qa-fundamentals",
            description: "Перші кроки в Selenium.",
            order: 5,
            estimatedTime: 30,
            xpReward: 15,
            hasQuiz: false,
            published: true,
          },
        ],
      },
    ],
  },
  // 2. AI Basics
  {
    courseSlug: "ai-basics",
    modules: [
      {
        id: "ai-intro-module",
        title: "Вступ до Штучного Інтелекту",
        order: 1,
        lessons: [
          {
            id: "ai-1",
            slug: "what-is-ai",
            title: "Що таке ШІ?",
            courseSlug: "ai-basics",
            description: "Загальне поняття про ШІ.",
            order: 1,
            estimatedTime: 15,
            xpReward: 10,
            hasQuiz: true,
            published: true,
          },
          {
            id: "ai-2",
            slug: "history-of-ai",
            title: "Історія ШІ",
            courseSlug: "ai-basics",
            description: "Як розвивався ШІ.",
            order: 2,
            estimatedTime: 20,
            xpReward: 10,
            hasQuiz: false,
            published: true,
          },
        ],
      },
      {
        id: "ml-basics-module",
        title: "Основи Машинного Навчання",
        order: 2,
        lessons: [
          {
            id: "ml-1",
            slug: "supervised-learning",
            title: "Навчання з учителем",
            courseSlug: "ai-basics",
            description: "Розберемо навчання з учителем.",
            order: 3,
            estimatedTime: 25,
            xpReward: 15,
            hasQuiz: true,
            published: true,
          },
          {
            id: "ml-2",
            slug: "unsupervised-learning",
            title: "Навчання без учителя",
            courseSlug: "ai-basics",
            description: "Розберемо навчання без учителя.",
            order: 4,
            estimatedTime: 25,
            xpReward: 15,
            hasQuiz: false,
            published: true,
          },
        ],
      },
    ],
  },
  // 3. Fullstack JavaScript
  {
    courseSlug: "fullstack-js",
    modules: [
      {
        id: "frontend",
        title: "Frontend розробка",
        order: 1,
        lessons: [
          {
            id: "fs-1",
            slug: "react-basics",
            title: "Основи React",
            courseSlug: "fullstack-js",
            description: "Створюємо перші компоненти.",
            order: 1,
            estimatedTime: 30,
            xpReward: 15,
            hasQuiz: true,
            published: true,
          },
          {
            id: "fs-2",
            slug: "react-hooks",
            title: "React Хуки",
            courseSlug: "fullstack-js",
            description: "useState, useEffect та інші.",
            order: 2,
            estimatedTime: 35,
            xpReward: 20,
            hasQuiz: true,
            published: true,
          },
          {
            id: "fs-3",
            slug: "state-management",
            title: "Керування станом",
            courseSlug: "fullstack-js",
            description: "Zustand, Redux або Context API.",
            order: 3,
            estimatedTime: 40,
            xpReward: 20,
            hasQuiz: false,
            published: true,
          },
        ],
      },
      {
        id: "backend",
        title: "Backend розробка",
        order: 2,
        lessons: [
          {
            id: "fs-4",
            slug: "nodejs-intro",
            title: "Вступ до Node.js",
            courseSlug: "fullstack-js",
            description: "Що таке Node.js і як він працює.",
            order: 4,
            estimatedTime: 25,
            xpReward: 15,
            hasQuiz: true,
            published: true,
          },
          {
            id: "fs-5",
            slug: "express-api",
            title: "Створення API з Express",
            courseSlug: "fullstack-js",
            description: "Будуємо REST API.",
            order: 5,
            estimatedTime: 45,
            xpReward: 25,
            hasQuiz: true,
            published: true,
          },
          {
            id: "fs-6",
            slug: "mongodb-basics",
            title: "Основи MongoDB",
            courseSlug: "fullstack-js",
            description: "Робота з NoSQL базою даних.",
            order: 6,
            estimatedTime: 40,
            xpReward: 20,
            hasQuiz: false,
            published: true,
          },
        ],
      },
    ],
  },
];
