export const featuredCourses = [
  {
    id: "1",
    slug: "qa-fundamentals",
    title: "Основи QA тестування",
    description: "Навчись тестувати ПЗ з нуля",
    level: "junior" as const,
    category: "qa" as const,
    thumbnail: "https://placehold.co/600x400/8BE9FD/282A36?text=QA",
    estimatedTime: 480,
    totalXP: 250,
    tags: ["testing", "qa", "manual"],
    published: true,
    lessonsCount: 25,
  },
  {
    id: "2",
    slug: "ai-basics",
    title: "Вступ до AI",
    description: "Основи машинного навчання",
    level: "junior" as const,
    category: "ai" as const,
    thumbnail: "https://placehold.co/600x400/BD93F9/282A36?text=AI",
    estimatedTime: 360,
    totalXP: 200,
    tags: ["ai", "ml", "python"],
    published: true,
    lessonsCount: 18,
  },
  {
    id: "3",
    slug: "fullstack-js",
    title: "Fullstack JavaScript",
    description: "React, Node.js та MongoDB",
    level: "middle" as const,
    category: "fullstack" as const,
    thumbnail: "https://placehold.co/600x400/FF79C6/282A36?text=Fullstack",
    estimatedTime: 720,
    totalXP: 400,
    tags: ["react", "nodejs", "fullstack"],
    published: true,
    lessonsCount: 45,
  },
];
